### PR TITLE
added another test for task B - John Zhou

### PR DESCRIPTION
**Pull request by johnzhou1210**
I added another test for task B. sloppy.cpp is a unindented .cpp file

### CODE REVIEW

**Comment by emmyvese12** [comment]
Got it, I will merge the new branch now. -Emmy Veselinov

**Comment by johnzhou1210** [comment]
John Zhou

**Comment by johnzhou1210** [comment]
I added another test for task B. sloppy.cpp is a unindented .cpp file - John Zhou

**Comment by johnzhou1210** [comment]
I see that it is merged - John Zhou

**Comment by emmyvese12** [comment]
Yes, merge was successful, thank you. - Emmy Veselinov

**Pull request merged**
